// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NonvoyxonaERP.Data;

#nullable disable

namespace NonvoyxonaERP.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Davomat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Izoh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("KeldiVaqt")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("KetdiVaqt")
                        .HasColumnType("time");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("datetime2");

                    b.Property<string>("Smena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XodimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("XodimId");

                    b.ToTable("Davomatlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.IshAkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Holat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("datetime2");

                    b.Property<string>("Smena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XodimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("XodimId");

                    b.ToTable("IshAktlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.IshAktQator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrakMiqdor")
                        .HasColumnType("int");

                    b.Property<int>("HaqiqiyMiqdor")
                        .HasColumnType("int");

                    b.Property<int>("IshAktId")
                        .HasColumnType("int");

                    b.Property<int>("MaxsulotId")
                        .HasColumnType("int");

                    b.Property<int>("RejalashMiqdor")
                        .HasColumnType("int");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IshAktId");

                    b.HasIndex("MaxsulotId");

                    b.ToTable("IshAktQatorlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Kassa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Qoldiq")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Turi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Kassalar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Maosh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Avans")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HisoblanganMaosh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mukofot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Oy")
                        .HasColumnType("int");

                    b.Property<decimal>("Shtraf")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tolangan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TolashSana")
                        .HasColumnType("datetime2");

                    b.Property<int>("XodimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("XodimId");

                    b.ToTable("Maoshlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Maxsulot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Kategoryasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Narxi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlchovBirligi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Maxsulotlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Retsept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxsulotId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miqdori")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OlchovBirligi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XomashyoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaxsulotId");

                    b.HasIndex("XomashyoId");

                    b.ToTable("Retseptlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Savdo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Holat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("JamiSumma")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TochkaId")
                        .HasColumnType("int");

                    b.Property<string>("TolovTuri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XodimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TochkaId");

                    b.HasIndex("XodimId");

                    b.ToTable("Savdolar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.SavdoQator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxsulotId")
                        .HasColumnType("int");

                    b.Property<int>("Miqdor")
                        .HasColumnType("int");

                    b.Property<decimal>("Narx")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SavdoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaxsulotId");

                    b.HasIndex("SavdoId");

                    b.ToTable("SavdoQatorlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Taminotchi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Manzil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Qarz")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Taminotchilar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Tochka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Manzil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MasulId")
                        .HasColumnType("int");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasulId");

                    b.ToTable("Tochkalar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Holat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Izoh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TochkaId")
                        .HasColumnType("int");

                    b.Property<int>("XodimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TochkaId");

                    b.HasIndex("XodimId");

                    b.ToTable("Transferlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.TransferQator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxsulotId")
                        .HasColumnType("int");

                    b.Property<int>("QabulMiqdor")
                        .HasColumnType("int");

                    b.Property<int>("TransferId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YuborilganMiq")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaxsulotId");

                    b.HasIndex("TransferId");

                    b.ToTable("TransferQatorlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Xarajat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Izoh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KassaId")
                        .HasColumnType("int");

                    b.Property<string>("Kategorya")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Summa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("XodimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KassaId");

                    b.HasIndex("XodimId");

                    b.ToTable("Xarajatlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Xodim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktive")
                        .HasColumnType("bit");

                    b.Property<decimal>("AsosiyMaoshi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IshbayNarxi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IshgaKirgan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lavozimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaoshiTuri")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Xodimlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Xomashyo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MinDaraja")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("Miqdori")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("Narxi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlchovBirligi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Yaratilganvaqt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Xomashyolar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Davomat", b =>
                {
                    b.HasOne("NonvoyxonaERP.Domain.Entities.Xodim", "Xodim")
                        .WithMany("Davomatlar")
                        .HasForeignKey("XodimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Xodim");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.IshAkt", b =>
                {
                    b.HasOne("NonvoyxonaERP.Domain.Entities.Xodim", "Xodim")
                        .WithMany("IshAktlar")
                        .HasForeignKey("XodimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Xodim");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.IshAktQator", b =>
                {
                    b.HasOne("NonvoyxonaERP.Domain.Entities.IshAkt", "IshAkt")
                        .WithMany("Qatorlar")
                        .HasForeignKey("IshAktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NonvoyxonaERP.Domain.Entities.Maxsulot", "Maxsulot")
                        .WithMany("IsAktQatorlar")
                        .HasForeignKey("MaxsulotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IshAkt");

                    b.Navigation("Maxsulot");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Maosh", b =>
                {
                    b.HasOne("NonvoyxonaERP.Domain.Entities.Xodim", "Xodim")
                        .WithMany("Maoshlar")
                        .HasForeignKey("XodimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Xodim");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Retsept", b =>
                {
                    b.HasOne("NonvoyxonaERP.Domain.Entities.Maxsulot", "Maxsulot")
                        .WithMany("Retseptlar")
                        .HasForeignKey("MaxsulotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NonvoyxonaERP.Domain.Entities.Xomashyo", "Xomashyo")
                        .WithMany("Retseptlar")
                        .HasForeignKey("XomashyoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maxsulot");

                    b.Navigation("Xomashyo");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Savdo", b =>
                {
                    b.HasOne("NonvoyxonaERP.Domain.Entities.Tochka", "Tochka")
                        .WithMany("Savdolar")
                        .HasForeignKey("TochkaId");

                    b.HasOne("NonvoyxonaERP.Domain.Entities.Xodim", "Xodim")
                        .WithMany()
                        .HasForeignKey("XodimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tochka");

                    b.Navigation("Xodim");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.SavdoQator", b =>
                {
                    b.HasOne("NonvoyxonaERP.Domain.Entities.Maxsulot", "Maxsulot")
                        .WithMany("SavdoQatorlar")
                        .HasForeignKey("MaxsulotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NonvoyxonaERP.Domain.Entities.Savdo", "Savdo")
                        .WithMany("Qatorlar")
                        .HasForeignKey("SavdoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maxsulot");

                    b.Navigation("Savdo");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Tochka", b =>
                {
                    b.HasOne("NonvoyxonaERP.Domain.Entities.Xodim", "Masul")
                        .WithMany()
                        .HasForeignKey("MasulId");

                    b.Navigation("Masul");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("NonvoyxonaERP.Domain.Entities.Tochka", "Tochka")
                        .WithMany("Transferlar")
                        .HasForeignKey("TochkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NonvoyxonaERP.Domain.Entities.Xodim", "Xodim")
                        .WithMany()
                        .HasForeignKey("XodimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tochka");

                    b.Navigation("Xodim");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.TransferQator", b =>
                {
                    b.HasOne("NonvoyxonaERP.Domain.Entities.Maxsulot", "Maxsulot")
                        .WithMany()
                        .HasForeignKey("MaxsulotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NonvoyxonaERP.Domain.Entities.Transfer", "Transfer")
                        .WithMany("Qatorlar")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maxsulot");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Xarajat", b =>
                {
                    b.HasOne("NonvoyxonaERP.Domain.Entities.Kassa", "Kassa")
                        .WithMany()
                        .HasForeignKey("KassaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NonvoyxonaERP.Domain.Entities.Xodim", "Xodim")
                        .WithMany()
                        .HasForeignKey("XodimId");

                    b.Navigation("Kassa");

                    b.Navigation("Xodim");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.IshAkt", b =>
                {
                    b.Navigation("Qatorlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Maxsulot", b =>
                {
                    b.Navigation("IsAktQatorlar");

                    b.Navigation("Retseptlar");

                    b.Navigation("SavdoQatorlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Savdo", b =>
                {
                    b.Navigation("Qatorlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Tochka", b =>
                {
                    b.Navigation("Savdolar");

                    b.Navigation("Transferlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Transfer", b =>
                {
                    b.Navigation("Qatorlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Xodim", b =>
                {
                    b.Navigation("Davomatlar");

                    b.Navigation("IshAktlar");

                    b.Navigation("Maoshlar");
                });

            modelBuilder.Entity("NonvoyxonaERP.Domain.Entities.Xomashyo", b =>
                {
                    b.Navigation("Retseptlar");
                });
#pragma warning restore 612, 618
        }
    }
}
